import { apiClient } from "@/lib/api-client";
import { Discount, ApiResponse } from "@/types";

export const discountService = {
  getDiscounts: async (): Promise<ApiResponse<Discount[]>> => {
    return apiClient.get<Discount[]>("/discounts");
  },

  getDiscountById: async (id: string): Promise<ApiResponse<Discount>> => {
    return apiClient.get<Discount>(`/discounts/${id}`);
  },

  createDiscount: async (discount: Omit<Discount, "id"> & { id?: string }): Promise<ApiResponse<Discount>> => {
    // If id is not supplied on front-end, let's create a random alphanumeric code or generate uuid on client side or let backend generate it if backend permits.
    // The model Discount.java has @Id String id, which is usually not auto-generated by jakarta unless specified.
    // Let's generate a clean random string id on client-side if it is missing.
    const payload = {
      ...discount,
      id: discount.id || "DISC-" + Math.random().toString(36).substring(2, 9).toUpperCase(),
    };
    return apiClient.post<Discount>("/discounts", payload);
  },

  updateDiscount: async (id: string, discount: Partial<Discount>): Promise<ApiResponse<Discount>> => {
    return apiClient.put<Discount>(`/discounts/${id}`, discount);
  },

  deleteDiscount: async (id: string): Promise<ApiResponse<void>> => {
    return apiClient.delete<void>(`/discounts/${id}`);
  },

  getActiveDiscounts: async (): Promise<ApiResponse<Discount[]>> => {
    return apiClient.get<Discount[]>("/discounts/active");
  }
};
